name: Checkout
on: [push]

jobs:
  checkout-action:
    runs-on: ubuntu-latest
    steps: 
      - name: List Files before
        run: ls -a
      - uses: actions/checkout@v3
      - name: List files after
        run: ls -a
  checkout-and-display-files:
    runs-on: ubuntu-latest
    steps:
      - name: List Files before checkout
        run: |
          echo "Files before checkout:"
          ls -a
      - name: Checkout Repository
        run: |
          git init
          git remote add origin "https://$GITHUB_ACTOR:${{ secrets.GITHUB_TOKEN}}@github.com/$GITHUB_REPOSITORY.git"
          git fetch origin
          git checkout main
      - name: List Files after checkout
        run: ls -a