name: Dynamic Matrix
on:
  workflow_dispatch: 
    inputs:
      os: 
        description: operating systems
        default: "windows_latest,ubuntu-latest"
        type: string
      node-version:
        description: Node version
        default: "14,15,16"
        type: string

jobs:
  prepare-matrix:
    runs-on: ubuntu-latest
    outputs: # outputs from this job to be used in another job
      matrix-arrays-output: ${{ steps.matrix-arrays.outputs.result }}
    steps:
      - uses: actions/github-script@v6
        id: matrix-arrays
        with:
          script: "return {os: context.payload.inputs['os'].split(','),
            'node-version': context.payload.inputs['node-version'].split(',') }"   # converts to array as os below expects arrays
          result-encoding: json 
      - run: echo '${{ steps.matrix-arrays.outputs.result }}'  
  node-matrix:
    needs: prepare-matrix
    strategy:
      matrix:
        os: ${{ fromJson(needs.prepare-matrix.outputs.matrix-arrays-output).os }}
        node-version: ${{ fromJson(needs.prepare-matrix.outputs.matrix-arrays-output).node-version }}
    runs-on: ${{ matrix.os }}
    steps:
      - run: node -v
      - uses: actions/setup-node@v3
        with: 
          node-version: ${{ matrix.node-version }}
      - run: node -v