name: Status Check Functions
on: [push]

jobs:
  job-1:
    runs-on: ubuntu-latest
    steps:
      - name: Step 1
        run: sleep 20
      - name: Step 2
        id: step-2
        run: exit 1
      - name: Runs on failure
        # Below failure() to be checked as all if condition have success as default behavior
        if: failure() && steps.step-2.conclusion == 'failure'
        run: echo "Step 2 has failed"
      - name: Runs on success
        # This if is not needed (DEFAULT BEHAVIOUR)
        if: success()
        run: echo "Runs on success, which is the default behavior."
      - name: Always Runs
        if: always()
        run: echo 'Always Runs'
      - name: Runs When Cancelled
        if: cancelled()
        run: echo 'Runs When Cancelled'

  job-2:
    runs-on: ubuntu-latest
    needs: job-1
    if: failure()
    steps: 
      - run: echo 'Job 2'